// Generated by CoffeeScript 1.6.3
var BAKAZE_TO_STR, TSUPAIS, TSUPAI_TO_IMAGE_NAME, cloneBoard, comparePais, currentActionId, currentKyokuId, currentViewpoint, deleteTehai, dumpBoard, getCurrentKyoku, goBack, goNext, initPlayers, kyokus, loadAction, paiToImageUrl, parsePai, playerInfos, removeRed, renderAction, renderCurrentAction, renderHo, renderPai, renderPais, ripai, sortPais, _base, _base1;

window.console || (window.console = {});

(_base = window.console).log || (_base.log = function() {});

(_base1 = window.console).error || (_base1.error = function() {});

TSUPAIS = [null, "E", "S", "W", "N", "P", "F", "C"];

TSUPAI_TO_IMAGE_NAME = {
  "E": "ji_e",
  "S": "ji_s",
  "W": "ji_w",
  "N": "ji_n",
  "P": "no",
  "F": "ji_h",
  "C": "ji_c"
};

BAKAZE_TO_STR = {
  "E": "東",
  "S": "南",
  "W": "西",
  "N": "北"
};

nextDoraPai = function(pai) {
  var i, m, n, zi;
  if (pai === "5mr" || pai === "5pr" || pai === "5sr") {
    return pai.charAt(0) + pai.charAt(1);
  }
  if ((m = pai.match(/^([1-9])(m|p|s)$/))) {
    n = parseInt(m[1]);
    return "" + ((n % 9) + 1) + m[2];
  }
  zi = ["E", "S", "W", "N", "P", "F", "C"];
  i = zi.indexOf(pai);
  return zi[(i + 1) % zi.length];
};

kyokus = [];

currentKyokuId = 0;

currentActionId = 0;

currentViewpoint = 0;

playerInfos = [{}, {}, {}, {}];

TILE_NAME = {
  "1m": "1万", "2m": "2万", "3m": "3万", "4m": "4万", "5m": "5万", "6m": "6万", "7m": "7万", "8m": "8万", "9m": "9万",
  "1p": "1筒", "2p": "2筒", "3p": "3筒", "4p": "4筒", "5p": "5筒", "6p": "6筒", "7p": "7筒", "8p": "8筒", "9p": "9筒",
  "1s": "1索", "2s": "2索", "3s": "3索", "4s": "4索", "5s": "5索", "6s": "6索", "7s": "7索", "8s": "8索", "9s": "9索",
  "E": "东", "S": "南", "W": "西", "N": "北", "P": "白", "F": "发", "C": "中",
  "5mr": "赤5万", "5pr": "赤5筒", "5sr": "赤5索"
};

PAI_BY_ID = [
  "1m", "2m", "3m", "4m", "5m", "6m", "7m", "8m", "9m",
  "1p", "2p", "3p", "4p", "5p", "6p", "7p", "8p", "9p",
  "1s", "2s", "3s", "4s", "5s", "6s", "7s", "8s", "9s",
  "E", "S", "W", "N", "P", "F", "C",
  "5mr", "5pr", "5sr"
];

paiToId = function(pai) {
  var kind, m, zi;
  if ((m = pai.match(/^([1-9])(m|p|s)$/))) {
    kind = { m: 0, p: 1, s: 2 }[m[2]];
    return kind * 9 + (parseInt(m[1]) - 1);
  }
  if (pai === "5mr") {
    return 34;
  }
  if (pai === "5pr") {
    return 35;
  }
  if (pai === "5sr") {
    return 36;
  }
  zi = { E: 27, S: 28, W: 29, N: 30, P: 31, F: 32, C: 33 };
  return zi[pai];
};

qValueForActionId = function(meta, id) {
  var bits, i, qs, rank;
  if (!meta || !meta.q_values || meta.mask_bits == null) {
    return null;
  }
  qs = meta.q_values;
  bits = BigInt(meta.mask_bits);
  if (id < 0 || id > 45 || !((bits >> BigInt(id)) & 1n)) {
    return null;
  }
  rank = 0;
  for (i = 0; i <= id; i++) {
    if ((bits >> BigInt(i)) & 1n) {
      rank++;
    }
  }
  return qs[rank - 1];
};

alignText = function(s) {
  var i, w, _i, _len;
  w = 0;
  for (i = _i = 0, _len = s.length; _i < _len; i = ++_i) {
    if (s.charCodeAt(i) > 255) {
      w += 2;
    } else {
      w++;
    }
  }
  return s + " ".repeat(Math.max(0, 7 - w));
};

listDiscardValues = function(meta) {
  var bits, e, entries, i, qs, rank, tile, _i, _results;
  if (!meta || !meta.q_values || meta.mask_bits == null) {
    return null;
  }
  qs = meta.q_values;
  bits = BigInt(meta.mask_bits);
  entries = [];
  rank = 0;
  for (i = _i = 0; _i < 37; i = ++_i) {
    if ((bits >> BigInt(i)) & 1n) {
      entries.push({ id: i, value: qs[rank] });
      rank++;
    }
  }
  if (entries.length === 0) {
    return null;
  }
  entries.sort(function(a, b) {
    return b.value - a.value;
  });
  _results = [];
  for (e in entries) {
    tile = PAI_BY_ID[entries[e].id];
    _results.push("  " + alignText(TILE_NAME[tile]) + entries[e].value.toFixed(1).padStart(6));
  }
  return _results;
};

playerName = function(i) {
  var base, dup, j, n;
  if (playerInfos[i] && playerInfos[i].name != null) {
    base = playerInfos[i].name;
  } else {
    return "玩家" + (i + 1);
  }
  dup = 0;
  for (j = 0; j < 4; j++) {
    if (playerInfos[j] && playerInfos[j].name === base) {
      dup++;
    }
  }
  if (dup > 1) {
    n = 0;
    for (j = 0; j <= i; j++) {
      if (playerInfos[j] && playerInfos[j].name === base) {
        n++;
      }
    }
    return base + " " + n;
  }
  return base;
};

paiName = function(p) {
  return TILE_NAME[p] || p;
};

kyokuResultText = function(k) {
  var action, d, i, sign, t;
  for (i = k.actions.length - 1; i >= 0; i--) {
    action = k.actions[i];
    if (action.type === "ryukyoku") {
      return "流局";
    }
    if (action.type === "hora") {
      d = action.deltas[action.actor];
      sign = d > 0 ? "+" : "";
      t = action.target === action.actor ? "自摸" : "荣和";
      return t + " " + playerName(action.actor) + " " + sign + d;
    }
  }
  return "";
};

finalRankingText = function() {
  var a, i, j, k, ranks, scores, _i, _j, _k, _len;
  scores = [25000, 25000, 25000, 25000];
  for (i = _i = 0; _i < kyokus.length; i = ++_i) {
    for (j = _j = 0, _len = kyokus[i].actions.length; _j < _len; j = ++_j) {
      a = kyokus[i].actions[j];
      if (a.type === "start_kyoku") {
        for (k = _k = 0; _k < 4; k = ++_k) {
          scores[k] = a.scores[k];
        }
      } else if ((a.type === "hora" || a.type === "ryukyoku") && a.deltas) {
        for (k = 0; k < 4; k++) {
          scores[k] += a.deltas[k];
        }
      }
    }
  }
  ranks = [0, 1, 2, 3].map(function(k) {
    return { i: k, s: scores[k] };
  });
  ranks.sort(function(x, y) {
    return y.s - x.s;
  });
  return ranks.map(function(r, idx) {
    return (idx + 1) + "位 " + playerName(r.i) + " " + r.s;
  });
};

formatActionText = function(action, nextMeta) {
  var line, metaNote, v, valList;
  metaNote = function(meta) {
    var notes;
    if (!meta) {
      return "";
    }
    notes = [];
    if (meta.shanten != null) {
      notes.push("向听=" + meta.shanten);
    }
    if (meta.at_furiten != null) {
      notes.push(meta.at_furiten ? "振听!" : "非振听");
    }
    if (meta.is_greedy != null) {
      notes.push(meta.is_greedy ? "greedy" : "random");
    }
    return notes.length ? " [" + notes.join(" ") + "]" : "";
  };
  switch (action.type) {
    case "start_game":
      return "游戏开始\n" + action.names.map(function(n, i) {
        return "  " + i + ". " + n;
      }).join("\n");
    case "start_kyoku":
      return "第" + action.kyoku + "局 " + action.honba + "本场\n庄家: " + playerName(action.oya) + "\n宝牌指示牌: " + paiName(action.dora_marker);
    case "end_kyoku":
      return "本局结束";
    case "end_game":
      return "游戏结束";
    case "tsumo":
      valList = nextMeta ? listDiscardValues(nextMeta) : null;
      if (valList) {
        return playerName(action.actor) + " 摸牌: " + paiName(action.pai) + "\n候选出牌 value 排序:\n" + valList.join("\n");
      }
      return playerName(action.actor) + " 摸牌: " + paiName(action.pai);
    case "dahai":
      line = playerName(action.actor) + " 出牌: " + paiName(action.pai) + (action.tsumogiri ? " (摸切)" : "");
      v = qValueForActionId(action.meta, paiToId(action.pai));
      if (v != null) {
        line += " (" + v.toFixed(1) + ")";
      }
      line += metaNote(action.meta);
      valList = listDiscardValues(action.meta);
      if (valList) {
        return line + "\n候选出牌 value 排序:\n" + valList.join("\n");
      }
      return line;
    case "reach":
      return playerName(action.actor) + " 立直" + metaNote(action.meta);
    case "reach_accepted":
      return playerName(action.actor) + " 立直成立";
    case "chi":
      return playerName(action.actor) + " 吃 " + paiName(action.pai) + " 用 " + action.consumed.map(paiName).join(",");
    case "pon":
      return playerName(action.actor) + " 碰 " + paiName(action.pai) + " 用 " + action.consumed.map(paiName).join(",");
    case "ankan":
      return playerName(action.actor) + " 暗杠 " + action.consumed.map(paiName).join(",");
    case "daiminkan":
      return playerName(action.actor) + " 大明杠 " + paiName(action.pai) + " 从 " + name(action.target);
    case "kakan":
      return playerName(action.actor) + " 加杠 " + paiName(action.pai);
    case "hora":
      return playerName(action.actor) + " 和牌! " + (action.target === action.actor ? "自摸" : "荣和, 放铳=" + playerName(action.target)) + " 点差: " + action.deltas.join(",");
    case "ryukyoku":
      return "流局";
    case "dora":
      return "宝牌追加: " + paiName(action.dora_marker);
    case "none":
      return "无操作";
    default:
      return action.type;
  }
};

parsePai = function(pai) {
  if (pai.match(/^([1-9])(.)(r)?$/)) {
    return {
      type: RegExp.$2,
      number: parseInt(RegExp.$1),
      red: RegExp.$3 ? true : false
    };
  } else {
    return {
      type: "t",
      number: TSUPAIS.indexOf(pai),
      red: false
    };
  }
};

comparePais = function(lhs, rhs) {
  var lhsRep, parsedLhs, parsedRhs, rhsRep;
  parsedLhs = parsePai(lhs);
  lhsRep = parsedLhs.type + parsedLhs.number + (parsedLhs.red ? "1" : "0");
  parsedRhs = parsePai(rhs);
  rhsRep = parsedRhs.type + parsedRhs.number + (parsedRhs.red ? "1" : "0");
  if (lhsRep < rhsRep) {
    return -1;
  } else if (lhsRep > rhsRep) {
    return 1;
  } else {
    return 0;
  }
};

sortPais = function(pais) {
  return pais.sort(comparePais);
};

paiToImageUrl = function(pai, pose) {
  var ext, name, parsedPai, redSuffix;
  if (pai) {
    if (pai === "?") {
      name = "bk";
      ext = "gif";
    } else {
      parsedPai = parsePai(pai);
      if (parsedPai.type === "t") {
        name = TSUPAI_TO_IMAGE_NAME[pai];
      } else {
        redSuffix = parsedPai.red ? "r" : "";
        name = "" + parsedPai.type + "s" + parsedPai.number + redSuffix;
      }
      ext = parsedPai.red ? "png" : "gif";
    }
    if (pose === void 0) {
      pose = 1;
    }
    return "files/images/p_" + name + "_" + pose + "." + ext;
  } else {
    return "files/images/blank.png";
  }
};

cloneBoard = function(board) {
  var bk, bv, newBoard, newPlayer, pk, player, pv, _i, _len;
  newBoard = {};
  for (bk in board) {
    bv = board[bk];
    if (bk === "players") {
      newBoard[bk] = [];
      for (_i = 0, _len = bv.length; _i < _len; _i++) {
        player = bv[_i];
        newPlayer = {};
        for (pk in player) {
          pv = player[pk];
          newPlayer[pk] = pv;
        }
        newBoard[bk].push(newPlayer);
      }
    } else {
      newBoard[bk] = bv;
    }
  }
  return newBoard;
};

initPlayers = function(board) {
  var player, _i, _len, _ref, _results;
  _ref = board.players;
  _results = [];
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    player = _ref[_i];
    player.tehais = null;
    player.furos = [];
    player.ho = [];
    player.reach = false;
    _results.push(player.reachHoIndex = null);
  }
  return _results;
};

removeRed = function(pai) {
  if (!pai) {
    return null;
  }
  if (pai.match(/^(.+)r$/)) {
    return RegExp.$1;
  } else {
    return pai;
  }
};

loadAction = function(action) {
  var actorPlayer, board, furos, i, kyoku, pai, prevBoard, targetPlayer, _i, _j, _k, _l, _len, _len1, _m, _n, _o, _ref, _ref1, _ref2;
  if (kyokus.length > 0) {
    kyoku = kyokus[kyokus.length - 1];
    board = cloneBoard(kyoku.actions[kyoku.actions.length - 1].board);
  } else {
    kyoku = null;
    board = null;
  }
  if (board && ("actor" in action)) {
    actorPlayer = board.players[action.actor];
  } else {
    actorPlayer = null;
  }
  if (board && ("target" in action)) {
    targetPlayer = board.players[action.target];
  } else {
    targetPlayer = null;
  }
  switch (action.type) {
    case "start_game":
      for (i = _i = 0; _i < 4; i = ++_i) {
        playerInfos[i].name = action.names[i];
      }
      break;
    case "end_game":
      null;
      break;
    case "start_kyoku":
      kyoku = {
        actions: [],
        bakaze: action.bakaze,
        kyokuNum: action.kyoku,
        honba: action.honba,
        oya: action.oya
      };
      kyokus.push(kyoku);
      prevBoard = board;
      board = {
        players: [{}, {}, {}, {}],
        doraMarkers: [action.dora_marker]
      };
      initPlayers(board);
      for (i = _j = 0; _j < 4; i = ++_j) {
        board.players[i].tehais = action.tehais[i];
        if (prevBoard) {
          board.players[i].score = prevBoard.players[i].score;
        } else {
          board.players[i].score = 25000;
        }
      }
      break;
    case "end_kyoku":
      null;
      break;
    case "tsumo":
      actorPlayer.tehais = actorPlayer.tehais.concat([action.pai]);
      break;
    case "dahai":
      deleteTehai(actorPlayer, action.pai);
      actorPlayer.ho = actorPlayer.ho.concat([action.pai]);
      break;
    case "reach":
      actorPlayer.reachHoIndex = actorPlayer.ho.length;
      break;
    case "reach_accepted":
      actorPlayer.reach = true;
      break;
    case "chi":
    case "pon":
    case "daiminkan":
      targetPlayer.ho = targetPlayer.ho.slice(0, targetPlayer.ho.length - 1);
      _ref = action.consumed;
      for (_k = 0, _len = _ref.length; _k < _len; _k++) {
        pai = _ref[_k];
        deleteTehai(actorPlayer, pai);
      }
      actorPlayer.furos = actorPlayer.furos.concat([
        {
          type: action.type,
          taken: action.pai,
          consumed: action.consumed,
          target: action.target
        }
      ]);
      break;
    case "ankan":
      _ref1 = action.consumed;
      for (_l = 0, _len1 = _ref1.length; _l < _len1; _l++) {
        pai = _ref1[_l];
        deleteTehai(actorPlayer, pai);
      }
      actorPlayer.furos = actorPlayer.furos.concat([
        {
          type: action.type,
          consumed: action.consumed
        }
      ]);
      break;
    case "kakan":
      deleteTehai(actorPlayer, action.pai);
      actorPlayer.furos = actorPlayer.furos.concat([]);
      furos = actorPlayer.furos;
      for (i = _m = 0, _ref2 = furos.length; 0 <= _ref2 ? _m < _ref2 : _m > _ref2; i = 0 <= _ref2 ? ++_m : --_m) {
        if (furos[i].type === "pon" && removeRed(furos[i].taken) === removeRed(action.pai)) {
          furos[i] = {
            type: "kakan",
            taken: action.pai,
            consumed: action.consumed,
            target: furos[i].target
          };
        }
      }
      break;
    case "hora":
    case "ryukyoku":
      null;
      break;
    case "dora":
      board.doraMarkers = board.doraMarkers.concat([action.dora_marker]);
      break;
    case "error":
      null;
      break;
    default:
      throw "unknown action: " + action.type;
  }
  if (action.scores) {
    for (i = _n = 0; _n < 4; i = ++_n) {
      board.players[i].score = action.scores[i];
    }
  }
  if (kyoku) {
    for (i = _o = 0; _o < 4; i = ++_o) {
      if (action.actor !== void 0 && i !== action.actor) {
        ripai(board.players[i]);
      }
    }
    action.board = board;
    return kyoku.actions.push(action);
  }
};

deleteTehai = function(player, pai) {
  var idx;
  player.tehais = player.tehais.concat([]);
  idx = player.tehais.lastIndexOf(pai);
  if (idx < 0) {
    idx = player.tehais.lastIndexOf("?");
  }
  if (idx < 0) {
    throw "pai not in tehai";
  }
  return player.tehais[idx] = null;
};

ripai = function(player) {
  var pai;
  if (player.tehais) {
    player.tehais = (function() {
      var _i, _len, _ref, _results;
      _ref = player.tehais;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        pai = _ref[_i];
        if (pai) {
          _results.push(pai);
        }
      }
      return _results;
    })();
    return sortPais(player.tehais);
  }
};

dumpBoard = function(board) {
  var consumedStr, furo, hoStr, i, player, tehaisStr, _i, _j, _len, _ref, _results;
  _results = [];
  for (i = _i = 0; _i < 4; i = ++_i) {
    player = board.players[i];
    if (player.tehais) {
      tehaisStr = player.tehais.join(" ");
      _ref = player.furos;
      for (_j = 0, _len = _ref.length; _j < _len; _j++) {
        furo = _ref[_j];
        consumedStr = furo.consumed.join(" ");
        tehaisStr += " [" + furo.taken + "/" + consumedStr + "]";
      }
      console.log("[" + i + "] tehais: " + tehaisStr);
    }
    if (player.ho) {
      hoStr = player.ho.join(" ");
      _results.push(console.log("[" + i + "] ho: " + hoStr));
    } else {
      _results.push(void 0);
    }
  }
  return _results;
};

renderPai = function(pai, view, pose) {
  if (pose === void 0) {
    pose = 1;
  }
  view.attr("src", paiToImageUrl(pai, pose));
  switch (pose) {
    case 1:
      view.addClass("pai");
      return view.removeClass("laid-pai");
    case 3:
      view.addClass("laid-pai");
      return view.removeClass("pai");
    default:
      throw "unknown pose";
  }
};

renderPais = function(pais, view, poses) {
  var i, _i, _ref, _results;
  pais || (pais = []);
  poses || (poses = []);
  view.resize(pais.length);
  _results = [];
  for (i = _i = 0, _ref = pais.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
    _results.push(renderPai(pais[i], view.at(i), poses[i]));
  }
  return _results;
};

renderHo = function(player, offset, pais, view) {
  var i, reachIndex, _i, _ref, _results;
  if (player.reachHoIndex === null) {
    reachIndex = null;
  } else {
    reachIndex = player.reachHoIndex - offset;
  }
  view.resize(pais.length);
  _results = [];
  for (i = _i = 0, _ref = pais.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
    _results.push(renderPai(pais[i], view.at(i), i === reachIndex ? 3 : 1));
  }
  return _results;
};

renderAction = function(action) {
  var a, dir, furo, furoView, ho, i, infoView, j, k, kyoku, laidPos, nextMeta, pais, player, poses, view, wanpais, _i, _j, _k, _ref, _ref1, _ref2, _ref3;
  nextMeta = null;
  if (action.type === "tsumo") {
    k = getCurrentKyoku();
    a = k.actions[currentActionId + 1];
    if (a && a.type === "dahai" && a.meta && a.meta.q_values) {
      nextMeta = a.meta;
    }
  }
  $("#action-label").text(formatActionText(action, nextMeta));
  $("#log-label").text((action.logs && action.logs[currentViewpoint]) || "");
  kyoku = getCurrentKyoku();
  $("#kyoku-info").text(BAKAZE_TO_STR[kyoku.bakaze] + kyoku.kyokuNum + "局 " + kyoku.honba + "本场");
  for (i = _i = 0; _i < 4; i = ++_i) {
    player = action.board.players[i];
    view = Dytem.players.at((i - currentViewpoint + 4) % 4);
    infoView = Dytem.playerInfos.at(i);
    infoView.score.text(player.score);
    infoView.viewpoint.text(i === currentViewpoint ? "+" : "");
    view.headerName.text(playerName(i));
    view.headerScore.text(player.score);
    view.headerJikaze.text(BAKAZE_TO_STR[TSUPAIS[((i - kyoku.oya + 4) % 4) + 1]]);
    if (!player.tehais) {
      renderPais([], view.tehais);
      view.tsumoPai.hide();
    } else if (player.tehais.length % 3 === 2) {
      renderPais(player.tehais.slice(0, player.tehais.length - 1), view.tehais);
      view.tsumoPai.show();
      renderPai(player.tehais[player.tehais.length - 1], view.tsumoPai);
    } else {
      renderPais(player.tehais, view.tehais);
      view.tsumoPai.hide();
    }
    ho = player.ho || [];
    renderHo(player, 0, ho.slice(0, 6), view.hoRows.at(0).pais);
    renderHo(player, 6, ho.slice(6, 12), view.hoRows.at(1).pais);
    renderHo(player, 12, ho.slice(12), view.hoRows.at(2).pais);
    view.furos.resize(player.furos.length);
    if (player.furos) {
      j = player.furos.length - 1;
      while (j >= 0) {
        furo = player.furos[j];
        furoView = view.furos.at(player.furos.length - 1 - j);
        if (furo.type === "ankan") {
          pais = ["?"].concat(furo.consumed.slice(0, 2)).concat(["?"]);
          poses = [1, 1, 1, 1];
        } else {
          dir = (4 + furo.target - i) % 4;
          if ((_ref = furo.type) === "daiminkan" || _ref === "kakan") {
            laidPos = [null, 3, 1, 0][dir];
          } else {
            laidPos = [null, 2, 1, 0][dir];
          }
          pais = furo.consumed.concat([]);
          poses = [1, 1, 1];
          [].splice.apply(pais, [laidPos, laidPos - laidPos].concat(_ref1 = [furo.taken])), _ref1;
          [].splice.apply(poses, [laidPos, laidPos - laidPos].concat(_ref2 = [3])), _ref2;
        }
        renderPais(pais, furoView.pais, poses);
        --j;
      }
    }
  }
  wanpais = ["?", "?", "?", "?", "?", "?"];
  for (i = _j = 0, _ref3 = action.board.doraMarkers.length; 0 <= _ref3 ? _j < _ref3 : _j > _ref3; i = 0 <= _ref3 ? ++_j : --_j) {
    wanpais[i + 2] = action.board.doraMarkers[i];
  }
  renderPais(wanpais, Dytem.wanpais);
  return renderPais(action.board.doraMarkers.map(nextDoraPai), Dytem.doras);
};

getCurrentKyoku = function() {
  return kyokus[currentKyokuId];
};

renderCurrentAction = function() {
  var max = getCurrentKyoku().actions.length - 1;
  $("#action-range-label").text("0~" + max);
  return renderAction(getCurrentKyoku().actions[currentActionId]);
};

goNext = function() {
  if (currentActionId === getCurrentKyoku().actions.length - 1) {
    return;
  }
  ++currentActionId;
  $("#action-id-label").val(currentActionId);
  return renderCurrentAction();
};

goBack = function() {
  if (currentActionId === 0) {
    return;
  }
  --currentActionId;
  $("#action-id-label").val(currentActionId);
  return renderCurrentAction();
};

goNextDahai = function() {
  var actions, i;
  actions = getCurrentKyoku().actions;
  for (i = currentActionId + 1; i < actions.length; i++) {
    if (actions[i].type === "dahai") {
      currentActionId = i;
      $("#action-id-label").val(currentActionId);
      return renderCurrentAction();
    }
  }
};

$(function() {
  var action, bakazeStr, honba, i, j, kyokuNum, kyokuResult, label, playerInfoView, playerView, _i, _j, _k, _l, _len, _ref;
  $(window).bind("mousewheel", function(e) {
    e.preventDefault();
    if (e.originalEvent.wheelDelta < 0) {
      return goNext();
    } else if (e.originalEvent.wheelDelta > 0) {
      return goBack();
    }
  });
  $("#prev-button").click(goBack);
  $("#next-button").click(goNext);
  $("#next-dahai-button").click(goNextDahai);
  $("#go-button").click(function() {
    var max;
    currentActionId = parseInt($("#action-id-label").val());
    if (isNaN(currentActionId)) {
      currentActionId = 0;
    }
    max = getCurrentKyoku().actions.length - 1;
    currentActionId = Math.max(0, Math.min(currentActionId, max));
    $("#action-id-label").val(currentActionId);
    return renderCurrentAction();
  });
  $("#action-id-label").keydown(function(e) {
    if (e.keyCode === 13) {
      return $("#go-button").click();
    }
  });
  $("#last-button").click(function() {
    currentActionId = getCurrentKyoku().actions.length - 1;
    $("#action-id-label").val(currentActionId);
    return renderCurrentAction();
  });
  $("#kyokuSelector").change(function() {
    currentKyokuId = parseInt($("#kyokuSelector").val());
    currentActionId = 0;
    return renderCurrentAction();
  });
  $("#viewpoint-button").click(function() {
    currentViewpoint = (currentViewpoint + 1) % 4;
    return renderCurrentAction();
  });
  for (_i = 0, _len = allActions.length; _i < _len; _i++) {
    action = allActions[_i];
    loadAction(action);
  }
  Dytem.init();
  for (i = _j = 0; _j < 4; i = ++_j) {
    playerView = Dytem.players.append();
    playerView.addClass("player-" + i);
    for (j = _k = 0; _k < 3; j = ++_k) {
      playerView.hoRows.append();
    }
    playerInfoView = Dytem.playerInfos.append();
    playerInfoView.index.text(i);
    playerInfoView.name.text(playerName(i));
  }
  for (i = _l = 0, _ref = kyokus.length; 0 <= _ref ? _l < _ref : _l > _ref; i = 0 <= _ref ? ++_l : --_l) {
    bakazeStr = BAKAZE_TO_STR[kyokus[i].bakaze];
    honba = kyokus[i].honba;
    kyokuNum = kyokus[i].kyokuNum;
    label = "" + bakazeStr + kyokuNum + "局 " + honba + "本場";
    kyokuResult = kyokuResultText(kyokus[i]);
    if (kyokuResult) {
      label += " (" + kyokuResult + ")";
    }
    $("#kyokuSelector").get(0).options[i] = new Option(label, i);
  }
  $("#final-ranking").text(finalRankingText().join("\n"));
  console.log("loaded");
  return renderCurrentAction();
});
